### ISSUE TITLE
Users should be able to see at least past and future 99 years(days,months,years)

### ISSUE THREAD

**Issue by utkuc** [HelheimDev/Android#1]

**Comment by canberksakarya** [comment]
Issue has been solved while integrating the calendar to the android application. 
No exact number of years is available such can be seen to past and to past.
I will update the issue again as soon as find the exact number.

**Comment by canberksakarya** [comment]
Upon further inspectations it seems that the calendar application can show and work between the years 1900 and 2100. Therefor I am closing this issue as the results are very close to my expectations.
