### ISSUE TITLE
Implement "Event" feature for users so event can be created for specific date and time 

### ISSUE THREAD

**Issue by utkuc** [HelheimDev/Android#5]

**Comment by canberksakarya** [comment]
Event function has proved itself worthy of more work.
Event function is currently on test basis and therefor not added to the current version of the application and the publish date of the event function has been delayed until Sprint 2.

**Comment by canberksakarya** [comment]
Event function is fully working. However the connection between the application and the server is troublesome. Therefor events can be created but unable to be put to server.
